coala/documentation

Developers/Writing_Bears.rst, Users/Install.rst, Users/Tutorial.rst
Closes https://github.com/coala-analyzer/documentation/issues/59
=> Add kinds of bears to docs

.gitignore
https://github.com/coala-analyzer/documentation/issues/84
=> NEW: Add *.orig to .gitignore

Help/Getting_In_Touch.rst
Closes https://github.com/coala-analyzer/documentation/issues/45
=> Getting_In_Touch: Add information about issue discussions

Developers/Codestyle.rst
Fixes https://github.com/coala-analyzer/documentation/issues/95
=> Codestyle: Fixes typo

Help/FAQ.rst
Fixes https://github.com/coala-analyzer/documentation/issues/104
=> FAQ.rst: Fix broken links

Developers/External_Bears.rst, Developers/Git_Basics.rst, Developers/Review.rst, Developers/Self_Correcting_Bears.rst, Developers/Writing_Linter_Bears.rst
Closes https://github.com/coala-analyzer/documentation/issues/97
=> Typo fixing multiple sections of the documentation

Users/Tutorial.rst
Closes https://github.com/coala/coala/issues/2781
=> Tutorial: Fix typo "of"->"or" 

Developers/Newcomers_Guide.rst
Closes https://github.com/coala/documentation/issues/114
=> Newcomers_Guide: Mention profile picture

Users/coala_as_Git_Hook.rst
Changes the sentence,
Using git hooks coala
can be executed
automatically, ensuring
your code follows your
quality requirements
to Using a git hook,
coala can be executed
automatically, ensuring
your code follows your
quality requirements.
Closes https://github.com/coala/documentation/issues/117
=> coala_as_Git_Hook.html: Change sentence

Developers/Newcomers_Guide.rst
Fixes https://github.com/coala/documentation/issues/127
=> Newcomers_Guide.rst: Change testing bears link

Developers/Newcomers_Guide.rst
In http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html
Step 7 >
Congratulations! Your PR just got accepted! You’re awesome. Now you should go for a [low issue](http://coala.readthedocs.io/en/latest/Developers/tinyurl.com/coala-low) they are really rewarding!
URL to coala low issue is broken.
=> Developers/Newcomers_Guide: Fix broken link

Developers/Writing_Good_Commits.rst
For consistency.
Closes https://github.com/coala-analyzer/documentation/issues/66
=> Writing_Good_Commits: Add a dot

Developers/Newcomers_Guide.rst
Closes https://github.com/coala/documentation/issues/98
=> Newcomers_Guide.rst: Fix the broken link to Writing Bears guide

Users/Glob_Patterns.rst
Fixes https://github.com/coala/documentation/issues/73
=> Glob_Patterns.rst: Link to .coafile options

Developers/Git_Basics.rst
This can be done through the Github UI.
=> Git_Basics: Mention how to verify a rebase

.coafile
This finds more violations against our shortlog policy! Yeah! :)
=> .coafile: Add commit checking

Developers/Newcomers_Guide.rst
Closes https://github.com/coala/documentation/issues/164
=> Newcomers_Guide: Improve newcomer process

Developers/Newcomers_Guide.rst
Replaces ``work load`` with ``workload``
Closes https://github.com/coala/documentation/issues/184
=> Newcomers_Guide.rst: ``work load`` -> ``workload``

Developers/Newcomers_Guide.rst
Closes https://github.com/coala/documentation/issues/182
=> Newcomers_Guide.rst: Remove double newline

Developers/Writing_Bears.rst
Fixes https://github.com/coala-analyzer/documentation/issues/22
=> Writing_Bears: Add docs for all the metadata attributes

Developers/Writing_Bears.rst
Closes https://github.com/coala/documentation/issues/204
=> Writing_Bears: Use :attr: instead of :meth: with BEAR_DEPS

Developers/Newcomers_Guide.rst
Added note that user should be logged in before clicking on Newcomers link.
=> Updated Newcomers guide

Developers/Newcomers_Guide.rst
Newcomers: Fixed formatting issue
Closes: https://github.com/coala/documentation/issues/250
=> Added space for correct formating

Developers/Writing_Linter_Bears.rst
Closes https://github.com/coala/documentation/issues/266
=> Writing_Linter_Bears: Mention metadata attributes

Help/MAC_Hints.rst
Change all occurrences of words OSX and MAC into macOS
Closes: https://github.com/coala/documentation/issues/254
=> MAC_Hints.rst: Changed OSX and MAC into macOS

Help/FAQ.rst
Closes https://github.com/coala/documentation/issues/286
=> FAQ.rst: Move wiki content to this page

Developers/Writing_Bears.rst
Adds docs to install written coala-bears locally
Closes https://github.com/coala/documentation/issues/294
=> Writing_Bears.rst: Add install bear locally section

Developers/Bear_Installation_Tool.rst
Fixes https://github.com/coala/documentation/issues/302
=> Bear_Installation_Tool: Remove '--' from all cib commands

Users/Tutorial.rst
Add the hyperlink to globs, coalib/results/results_actions,
coalib/output.
Closes coala#113
=> Tutorial.rst: Add hyperlinks

index.rst
For doc entry `Linter Bears - Advanced`.
=> index.rst: Point doc entry to right link

Users/Glob_Patterns.rst
Fixes https://github.com/coala/documentation/issues/330
=> Globe_Patterns:Fix malformed table

Help/FAQ.rst, Users/Install.rst, Users/Tutorial.rst
Fixed all the Developer section links in following files
* Help/FAQ.rst
* Users/Install.rst
* Users/Tutorial.rst
Fixes https://github.com/coala/documentation/issues/349
=> Fix Links for Developer Section

Help/FAQ.rst, Users/Docker_Image.rst, index.rst
coala-format and coala-json also has been
changed to coala --format and coala --json.
Closes https://github.com/coala/documentation/issues/326
=> Change coala-ci to coala --ci

Help/FAQ.rst
This answer removes the analogy to LibreOffice.
coala's key features that previously created
clutter in the main paragraph, have been added
to the bullet points instead.
It emphasizes the two important points, making
it clear to users about what coala is and what
it does
Closes https://github.com/coala/documentation/issues/289
=> FAQ.rst: Shorten "What does coala do(for me)?"

Help/MAC_Hints.rst
Closes: https://github.com/coala/documentation/issues/383
=> MAC_Hints.rst: Documentation Error

Help/FAQ.rst
Closes https://github.com/coala/documentation/issues/376
=> FAQ.rst: Remove scrutinizer references

Help/FAQ.rst
Add Table of contents in FAQ.rst
Closes https://github.com/coala/documentation/issues/285
=> FAQ.rst: Add ToC

conf.py
Change year 2016 to 2017.
Closes https://github.com/coala/documentation/issues/417
=> conf.py: Update copyright year

Users/Install.rst
Adds note for not using apt for installing coala.
Closes https://github.com/coala/documentation/issues/392
- [ x ] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [ x ] I ran coala over my code locally. (*All commits have to pass
likely receive a lot of bot comments and build failures if coala does …
=> Install.rst: Add note for ubuntu users

Users/Install.rst
This link explains users about setting-up
tab-completion for coala arguements and bear names.
Closes https://github.com/coala/documentation/issues/386
them.
After you submit your pull request, **DO NOT click the 'Update Branch' …
=> Install.rst: Add link to bash/zsh auto-completion

Users/coafile.rst
Document the new section appending behavior added by the secinherit
patch series.
them. …
=> coafile.rst: Add section appending docs

.coafile, Users/coala_as_Git_Hook.rst
Enable RSTCheckBear in the .coafile
present in the documentation repo.
Closes https://github.com/coala/documentation/issues/432
them. …
=> .coafile: Enable RSTcheckBear 

Users/Install.rst
This updates the installing docs thus ensuring the OS X support for coala
Fixes https://github.com/coala/coala/issues/4272
them. …
=> Install.rst: Update support information for OS X

Users/Install.rst
=> Install.rst: Add link to pep440/version-specifiers

Help/FAQ.rst
Fixes #442.Added link to a list of exit codes and their meanings.
them. …
=> FAQ.rst: Adds reference to list of exit codes

Users/coafile.rst
Add the reason for deprecating implicit inheritance
and instead using explicit inheritance.
Closes https://github.com/coala/documentation/issues/428
them.
After you submit your pull request, **DO NOT click the 'Update Branch' …
=> coafile.rst: New section inheritance documentation

Help/MAC_Hints.rst
While doing fix for https://github.com/coala/coala/issues/3461 
I added Instruction to install pyenv and link to the issue @jayvdb mentioned
=> MAC_Hints.rst: Instruction to install pyenv added

Users/coafile.rst
This tells the user about configuration settings that can be
changed after learning the structure of coafiles.
Closes #446
them. …
=> coafile: Provide config settings link in end

.travis.yml, Help/FAQ.rst, conf.py, index.rst
Closes https://github.com/coala/documentation/issues/458
=> Travis Sphinx

Users/Tutorial.rst
Closes https://github.com/coala/documentation/issues/94
them.
instead. …
=> Tutorial: Mention how to set default editor

README.rst
Updated coala banner on README.md 
This PR fixes #436
=> Updated coala banner

Users/Docker_Image.rst
Added the line:"Docker does not support python 2
code analysis."
Closes https://github.com/coala/documentation/issues/477
them. …
=> Docker_Image.rst: Mention no support for Python 2

.coafile
=> .coafile: Ensure it has similar commit rules as main repo

Users/coafile.rst
File README.rst now documents
default_coafile.
Closes https://github.com/coala/coala/issues/3388
them. …
=> README.rst: Add default_coafile

Help/FAQ.rst, Users/Tutorial.rst, index.rst
Old link pointing to https://github.com/coala/bear-docs that is
deprecated.
Fixes https://github.com/coala/documentation/issues/495
them.
When asked …
=> Link: Update deprecated Bears documentation link

Users/Docker_Image.rst
This bash alias shows how to use coala docker image as alias
Closes https://github.com/coala/documentation/issues/358
them.
When asked for a rebase, …
=> Docker_Image: Add bash alias to docker docs

Users/Install.rst
This note helps the users who have both python2 and python3 installed.
Adds information to setup python3 only virtualenv.
Closes https://github.com/coala/documentation/issues/515
them.
After you submit your pull request, **DO NOT …
=> Install.rst: Add note for virtualenv creation

.gitignore, Users/Install.rst
Pipenv support is added for coala installation for Linux, Mac and Windows.
It helps manage pip and virtualenv together.
Closes https://github.com/coala/documentation/issues/502
=> Install.rst: Adding pipenv support

Users/Tutorial.rst
The use of `--apply-patches` is clearly explained.
Closes: https://github.com/coala/documentation/issues/35
them. …
=> Tutorial.rst: Documentation of `--apply-patches`

Help/FAQ.rst
FAQ.rst: Fix "ask us!" link
Fixes https://github.com/coala/documentation/issues/492
them. …
=> FAQ.rst: Fix "ask us!" link

README.rst
This adds virtualenv to the build procedure to make sure that the
documentation gets built with the correct python version.
Closes https://github.com/coala/documentation/issues/514
them.
After you submit your pull request, **DO NOT …
=> README.rst: Update build instructions

Users/coala_quickstart.rst, index.rst
This commit adds the doc for coala-quickstart
explaining its features, installation and
usage.
Closes https://github.com/coala/documentation/issues/42
cc @ishanSrt 
them.
After you submit your pull request, **DO NOT click the …
=> Add coala_quickstart.rst

Users/Tutorial.rst
This updates the documentation by removing all mentions of the, now
deprecated `Default` section and rewriting them using `cli` section.
Closes https://github.com/coala/coala/issues/5172
them.
After you submit your pull request, …
=> Tutorial.rst: Rewrite all mentions of Default

Help/FAQ.rst
This adds Code of Conduct item to FAQ.
Closes https://github.com/coala/documentation/issues/554
them. …
=> FAQ.rst: Add item about CoC

Users/coafile.rst
This changes the default_coafile to system_coafile in docs
Closes https://github.com/coala/documentation/issues/556
them.
When asked for a rebase, …
=> coafile.rst: Use system_coafile

.moban.yaml, Makefile, docs-requirements.txt, netlify.toml, requirements.txt
=> Sync moban

Help/FAQ.rst
This adds a brief description on what a bear is.
Closes https://github.com/coala/documentation/issues/284
them. …
=> FAQ.rst: Add question "What is a bear anyway?"

_static/images/coala_logo.svg
=> Sync Templates

Users/coafile.rst
This commit ensures that people recognize backslashes and forward slashes immediately.
For eg.
Forward slash - /
Backslash - \
Double Backslash - \\
Closes https://github.com/coala/documentation/issues/571
them.
After you submit …
=> coafile.rst:Add slashes

Users/Install.rst
Closes: #259 
them.
instead.
Please consider helping us by reviewing other …
=> Install.rst: Add Java Warning following Installation

Users/Docker_Image.rst
Users/Docker_Image.rst: update sample travis.yml
Updated sample travis.yml as described in issue.
Fixes #581 
them. …
=> Users/Docker_Image.rst: update sample travis.yml
