Developers/Writing_Good_Commits.rst
Remove "the" from lines 26-28 to improve readability.
Fixes https://github.com/coala-analyzer/documentation/issues/67
=> Writing_Good_Commits: Remove the word "the"

Developers/Codestyle.rst
We are already enfocing it, but it's not covered by PEP8
Fixes https://github.com/coala-analyzer/documentation/issues/27
=> Codestyle.rst: Add line continuation policy

Developers/Writing_Bears.rst
'get_dependencies' was an outdated function name.
This makes sure its name is up to date.
Fixes https://github.com/coala-analyzer/documentation/issues/83
=> Writing_Bears: Rename 'get_dependencies' to 'BEAR_DEPS'

Users/coafile.rst
'You can place a .coarc file in your home directory to set certain
settomgs user wide' was changed to
'You can place a .coarc file in your home directory to set certain
user wide settins'
Closes #119
=> coafile.rst: Change sentence in coafile

Developers/Development_Setup.rst
The link to the `coala-bears` and `coala` appears on the same line.
Hence, isn't really readable. This commit gives them both a different
line
=> Development_Setup.rst: Increase readability

Developers/Git_Basics.rst
Currently,a link in "Creating a Pull Request" section points
to dangling link in Git_Basics.rst.
This fix points document link to right location i.e., #rebasing
from same document.
Fixes : https://github.com/coala/documentation/issues/124
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
=> Git_Basics: Fix Rebase link in Git_Basics

Developers/Newcomers_Guide.rst
In Newcomers_Guide.rst the link is changed to http://coala.readthedocs.io/en/latest/Developers/Review.html
Fixes https://github.com/coala/documentation/issues/128
=> Newcomers_Guide.rst: Fix broken link

Developers/Executing_Tests.rst
Removes extra whitespace in shell command (line 31) in coala/documentation
/Developers/Executing_Tests.rst
Closes #103
=> Executing_Tests.rst: Remove redundant whitespace

Developers/Linter_Bears_Advanced.rst
Change the variable name value=2 to value2
Closes https://github.com/coala/documentation/issues/140
=> Linter_Bears_Advanced: Fix typo

Developers/Git_Basics.rst
Changes the link pointing to `Writing Good Commits`.
Fixes https://github.com/coala/documentation/issues/157
=> Git_Basics.rst : Fix broken link

_static/custom.css, conf.py
Update conf.py to use alabaster theme. Customize the sidebar,
and add git repository information
Closes https://github.com/coala/documentation/issues/99
Hi, please check, and let me know what you think.
Do test it on your own environment first :) 
Thanks.
Here's how it looks like on my local env.
=> Use alabaster Theme

README.rst
Closes #201 
Here is the change.
I think as maintainer you can also edit the description on directly on github eg
You can then add the docs url and press save.
I was able to do this in my forked repo see https://github.com/Mariatta/documentation
Thanks 😸
=> Mention coala docs url

Developers/Writing_Linter_Bears.rst
documentation/Developers/Writing_Linter_Bears.rst : Changed --msg_template...  to --msg-template...
This change was in response to an issue. The option --msg_template is wrong as the implementation is of --msg-template.
Fix for https://github.com/coala/documentation/issues/206
=> Updated Writing_Linter_Bears.rst

Developers/Newcomers_Guide.rst
It adds a guideline to not to delete comments on github
because it makes it hard for other developers to follow.
Closes https://github.com/coala/documentation/issues/219
=> Newcomers_Guide.rst: Add a guideline

Developers/Writing_Bears.rst
The bear is a python file and should have a ``.py`` extension.
Closes https://github.com/coala/documentation/issues/224
=> Writing_Bears: Add ``.py`` to ``HelloWorldBear``

Developers/Writing_Bears.rst
Cache has to be flushed when files have been
already analyzed and the coala command is used with a new bear.
Closes https://github.com/coala/documentation/issues/225
=> Writing_Bears.rst: Add flush-cache option

Users/Tutorial.rst
Explicitly mention where the trailing whitespace is, so the reader
can not be confused. Remove the confusing 'two results' text, as it
prints only one result.
Closes https://github.com/coala/documentation/issues/234
=> Tutorial.rst: Explain more trailing space removal

Developers/Writing_Bears.rst
Unifying grammatical ending of list items for the "Communicating with
the User" section.
Closes https://github.com/coala/documentation/issues/233
=> Writing_Bears: Add period to list item

Developers/Writing_Good_Commits.rst
It adds a quick reference of `how to write good commits`.
Closes https://github.com/coala/documentation/issues/72
=> Writing_Good_Commits.rst: Modify the doc

_static/custom.css
Make the link to  the current page bold to distinguish it from inactive pages.
Let me know if this works.
Closes #262
=> Highlight current page in the navigation menu

Developers/Development_Setup.rst, Users/Tutorial.rst
Hyperlink "virtualenv setup" in Developers/Development_Setup.rst refer to MAC Hints virtual environment setup and "supported languages" in Users/Tutorials.rst refer to supported languages doc page on github.
=> Fix hyperlink in Developers/Development_Setup.rst and Users/Tutorials.rst #247

_static/custom.css
Make the logo fill entire nav column.
Hope this works :)
Thanks.
Closes #216
=> Resize the width of the logo

Users/Glob_Patterns.rst
It removes some unnecessary examples.
Closes https://github.com/coala/documentation/issues/70
=> Glob_Patterns.rst: Remove redundant examples

Developers/Writing_Good_Commits.rst
Specify 'each line' for the length of commit body character limit
Closes https://github.com/coala/documentation/issues/308
=> Developers/Writing_Good_Commits: Add body length

index.rst
Replace outdated Developers toc with link to
api documentation
Closes https://github.com/coala/documentation/issues/342
=> Add link to api.coala.io

Users/Install.rst
This doesn't work because the $(pwd) will be evaluated when running the
alias command.
This is a hotfix.
=> Install: Remove alias section

Users/Install.rst
Changes the pip3 command to git clone under venv when installing because
it fails when installing dependencies.
=> Install: Changes install command under venv

Users/Tutorial.rst
Added details about the keyword 'noqa'
along with related examples. It has the
same functionality as 'ignore'
Closes #366
=> Tutorial.rst: Add 'noqa' and examples

Users/Glob_Patterns.rst
Glob_Patterns: Got rid of extra escapes
Closes https://github.com/coala/documentation/issues/371
=> Closes https://github.com/coala/documentation/issues/371

index.rst
Added small description for --json and --format
when used with coala command. 
Closes https://github.com/coala/documentation/issues/278
=> index.rst: Add hint to use --json and --format

Users/Docker_Image.rst
Add configuration information for Circle CI on use
of the `coala/base` docker image.
Closes #379
=> Docker_Image.rst: Add configuration for Circle CI

Users/Tutorial.rst
Change in command to show that `--show-bears
--filter-by-language` can accept multiple
languages as arguments.
Closes https://github.com/coala/documentation/issues/34
=> Tutorial.rst: Modify example

Users/Tutorial.rst
'--show-description' does not display a large amount
of information regarding the bears that have been
specified (in the .coafile or in the CLI arguments),
since it shows bear descriptions for '--show-bears'.
This has been replaced by '--show-details'.
Closes https://github.com/coala/documentation/issues/397
=> Tutorial.rst: Update Show bears' Information

Users/Shell_Autocompletion.rst
The `argcomplete` package expects a script name, not a path (neither
relative, not absolute). Using `which coala` returns a path. Instead,
use just `coala` to register with `register-python-argcomplete`.
Related `argcomplete` documentation:
https://argcomplete.readthedocs.io/en/latest/#synopsis
Related discussion with `argcomplete` devs
https://github.com/kislyuk/argcomplete/issues/212
Fixes https://github.com/coala/documentation/issues/388
them.
individually.* It is not …
=> Shell_Autocompletion.rst: Drop `which coala`

Users/Install.rst
This commit fixes the Windows docker install link to use the correct rst format instead of markdown.
It also does some grammar corrections in the affected sentence.
Fixes https://github.com/coala/documentation/issues/433
them. …
=> Install.rst: Fix Windows docker instructions

Users/Tutorial.rst
Users/Tutorial.rst: Output examples added
Added the examples of output when a user runs coala
on coala-tutorial code.
Closes https://github.com/coala/coala/issues/4254
=> Users/Tutorial.rst: Output examples added

_templates/searchbox.html
This template overrides the default searchbox.html template shipped with
sphinx hence, allowing usage of custom search like DocSearch.
Closes https://github.com/coala/documentation/issues/463
them.
After you submit your pull …
=> searchbox.html: Use docsearch instead of default

Users/coafile.rst
Relates to https://github.com/coala/coala/issues/4665
=> coafile.rst: Add aspects section

Users/Docker_Image.rst
Added explanation for Docker.
Closes https://github.com/coala/documentation/issues/30
them. …
=> docs: Clarify the coala in a container docs

Users/coala_as_Git_Hook.rst
Remove the $ sign from the beginning of each line in the .git/hooks/pre-commit file example.
Fixes https://github.com/coala/documentation/issues/538
=> Update pre-commit hook example

PULL_REQUEST_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md: cobot --> corobo 
Closes https://github.com/coala/documentation/issues/503
=> PULL_REQUEST_TEMPLATE.md: cobot --> corobo

index.rst
index.rst: Correct grammatical error
This corrects the typo and changes it from an user --> a user.
Closes https://github.com/coala/documentation/issues/516
=> Correct grammatical error: an user --> a user

Users/Tutorial.rst
Replaced the deprecated ```[Default]``` section by ```[cli]```. Also, assigned ```True``` to ```use_spaces``` instead of ```yeah```.
These changes were made because the previous documentation was inconsistent with the observation upon execution of coala.
Fixes https://github.com/coala/coala/issues/4968
them.
likely receive a lot of …
=> Tutorial.rst: Change documentation about .coafile

Users/coafile.rst
The changes were made to the documentation of coafile.rst . 
There was a bad codeblock markup at "[section1] # setting1 is inherited setting2 = 2". 
Changed it to "[section1] # setting1 is inherited setting2 = 2::"
them.
After you …
=> coafile.rst: Fix bad code markup

Users/Docker_Image.rst
Fixed copyright violation in Users/Docker_Image.rst by referencing the
source and added refernce to CC-BY-SA 4.0 license 
Closes https://github.com/coala/documentation/issues/482
them.
After you submit your pull request, **DO NOT …
=> Users/Docker_Image.rst: Fix copyright violation

Help/Getting_In_Touch.rst
=> Getting_In_Touch.rst: Add COC reference link.

Users/Glob_Patterns.rst, Users/Install.rst, Users/Tutorial.rst
This changes direct links to relative links to the internal page.
Closes https://github.com/coala/documentation/issues/595
them. …
=> Glob_Patterns.rst/Install.rst/Tutorial.rst: Fix external links which point to internal pages
